# fly.toml app configuration file generated for gym-tracker-wild-sound-6248 on 2026-03-28T15:17:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gym-tracker-wild-sound-6248'
primary_region = 'lhr'

[build]

[env]
  AI_PROVIDER = 'google'
  NODE_ENV = 'production'
  PORT = '3000'

[mounts]
  source = 'tailscale_state'
  destination = '/var/lib/tailscale'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
